# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarm" do
  version "0.15.1"

  on_macos do
    sha256 "f23ab08ecd3654dd009ead687603212107ad747eeb517658acaeb02f43d9a9e7"
    url "https://github.com/Nathandela/swarm/releases/download/v#{version}/swarm_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "43c951b21b09cdb6aced6e6cfe35ccf48e56d37dffe34f38e1f51ce049be91e2"
      url "https://github.com/Nathandela/swarm/releases/download/v#{version}/swarm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "465887e7f586d1cd0f3e61e9e89c51e9125d140398cd2dcd95f118cb7baafbe2"
      url "https://github.com/Nathandela/swarm/releases/download/v#{version}/swarm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "swarm"
  desc "Every coding agent on your machine, in one keyboard-driven terminal view"
  homepage "https://github.com/Nathandela/swarm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarm"
  binary "swarm-remote"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
