# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarm" do
  version "0.13.7"

  on_macos do
    sha256 "5f9f228eafe77c6c5e67568a52b7bd46a1abd2c5dff0b6922828b4cd30cd1ce1"
    url "https://github.com/Nathandela/swarm/releases/download/v#{version}/swarm_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "3db5a28ba766619fa3ad820ac74b2b08e730e883296779a4922cbdc1a932d147"
      url "https://github.com/Nathandela/swarm/releases/download/v#{version}/swarm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "31ba984be46d965a065f5110dbc8f78b2f99a2e447f27ad145f4230c83793d5a"
      url "https://github.com/Nathandela/swarm/releases/download/v#{version}/swarm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "swarm"
  desc "Every coding agent on your machine, in one keyboard-driven terminal view"
  homepage "https://github.com/Nathandela/swarm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarm"
  binary "swarm-remote"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
