# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarm" do
  version "0.13.3"

  on_macos do
    sha256 "3c8f0e2487e402a23360ad53b4ace48aca8b38c1db392ed448fcb09543c78ed8"
    url "https://github.com/Nathandela/swarm/releases/download/v#{version}/swarm_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "e092a96c0b7214e1d45c7f6997aae6014c275134c5a09f65d483583db38165ac"
      url "https://github.com/Nathandela/swarm/releases/download/v#{version}/swarm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa03760349357ec9a82282e0481f807f10738262e6dcacceea0f9967b30b6ad8"
      url "https://github.com/Nathandela/swarm/releases/download/v#{version}/swarm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "swarm"
  desc "Every coding agent on your machine, in one keyboard-driven terminal view"
  homepage "https://github.com/Nathandela/swarm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarm"
  binary "swarm-remote"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
